name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/group_2_x2.svg
    - assets/vectors/group_4_x2.svg
    - assets/vectors/group_21_x2.svg
    - assets/vectors/group_1_x2.svg
    - assets/vectors/group_6_x2.svg
    - assets/vectors/vector_4_x2.svg
    - assets/vectors/group_26_x2.svg
    - assets/vectors/group_11_x2.svg
    - assets/vectors/group_17_x2.svg
    - assets/vectors/vector_99_x2.svg
    - assets/vectors/vector_59_x2.svg
    - assets/vectors/group_8_x2.svg
    - assets/vectors/group_28_x2.svg
    - assets/vectors/group_27_x2.svg
    - assets/vectors/group_19_x2.svg
    - assets/vectors/group_12_x2.svg
    - assets/vectors/group_10_x2.svg
    - assets/vectors/group_5_x2.svg
    - assets/vectors/group_7_x2.svg
    - assets/vectors/group_25_x2.svg
    - assets/vectors/group_29_x2.svg
    - assets/vectors/vector_97_x2.svg
    - assets/vectors/group_32_x2.svg
    - assets/vectors/group_9_x2.svg
    - assets/vectors/group_20_x2.svg
    - assets/vectors/group_13_x2.svg
    - assets/vectors/group_16_x2.svg
    - assets/vectors/group_14_x2.svg
    - assets/vectors/group_18_x2.svg
    - assets/vectors/group_24_x2.svg
    - assets/vectors/group_23_x2.svg
    - assets/vectors/group_15_x2.svg
    - assets/vectors/group_31_x2.svg
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/group_x2.svg
    - assets/vectors/vector_45_x2.svg
    - assets/vectors/group_22_x2.svg
    - assets/images/image_171.png
    - assets/vectors/vector_103_x2.svg
    - assets/vectors/vector_84_x2.svg
    - assets/vectors/vector_69_x2.svg
    - assets/vectors/vector_74_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/vector_61_x2.svg
    - assets/vectors/vector_5_x2.svg
    - assets/vectors/vector_101_x2.svg
    - assets/vectors/vector_51_x2.svg
    - assets/vectors/vector_41_x2.svg
    - assets/vectors/map_1_x2.svg
    - assets/vectors/vector_104_x2.svg
    - assets/vectors/vector_64_x2.svg
    - assets/vectors/vector_1_x2.svg
    - assets/vectors/vector_98_x2.svg
    - assets/vectors/vector_81_x2.svg
    - assets/vectors/vector_92_x2.svg
    - assets/vectors/vector_48_x2.svg
    - assets/vectors/vector_87_x2.svg
    - assets/vectors/vector_119_x2.svg
    - assets/images/image_171.png
    - assets/vectors/vector_120_x2.svg
    - assets/vectors/vector_20_x2.svg
    - assets/vectors/vector_65_x2.svg
    - assets/vectors/vector_100_x2.svg
    - assets/vectors/vector_121_x2.svg
    - assets/vectors/vector_23_x2.svg
    - assets/vectors/vector_22_x2.svg
    - assets/vectors/vector_77_x2.svg
    - assets/vectors/vector_82_x2.svg
    - assets/vectors/vector_86_x2.svg
    - assets/vectors/vector_78_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/vectors/vector_70_x2.svg
    - assets/vectors/vector_85_x2.svg
    - assets/vectors/star_3_x2.svg
    - assets/vectors/vector_122_x2.svg
    - assets/vectors/vector_38_x2.svg
    - assets/vectors/vector_107_x2.svg
    - assets/vectors/vector_52_x2.svg
    - assets/vectors/vector_43_x2.svg
    - assets/vectors/vector_57_x2.svg
    - assets/vectors/vector_36_x2.svg
    - assets/vectors/vector_71_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/vector_116_x2.svg
    - assets/vectors/image_splash_x2.svg
    - assets/images/image_15.png
    - assets/vectors/star_2_x2.svg
    - assets/vectors/star_11_x2.svg
    - assets/vectors/container_x2.svg
    - assets/vectors/rectangle_1481_x2.svg
    - assets/vectors/vector_68_x2.svg
    - assets/vectors/vector_46_x2.svg
    - assets/vectors/vector_91_x2.svg
    - assets/vectors/vector_26_x2.svg
    - assets/vectors/vector_106_x2.svg
    - assets/vectors/vector_53_x2.svg
    - assets/images/image_171.png
    - assets/images/image_17.png
    - assets/vectors/vector_60_x2.svg
    - assets/vectors/vector_89_x2.svg
    - assets/vectors/vector_39_x2.svg
    - assets/vectors/vector_27_x2.svg
    - assets/vectors/vector_2_x2.svg
    - assets/vectors/vector_44_x2.svg
    - assets/vectors/vector_114_x2.svg
    - assets/vectors/vector_94_x2.svg
    - assets/vectors/vector_73_x2.svg
    - assets/vectors/vector_15_x2.svg
    - assets/vectors/vector_34_x2.svg
    - assets/vectors/vector_117_x2.svg
    - assets/images/image_15.png
    - assets/vectors/star_1_x2.svg
    - assets/vectors/container_1_x2.svg
    - assets/vectors/star_21_x2.svg
    - assets/vectors/vector_108_x2.svg
    - assets/vectors/vector_21_x2.svg
    - assets/vectors/vector_8_x2.svg
    - assets/vectors/vector_37_x2.svg
    - assets/vectors/vector_40_x2.svg
    - assets/vectors/vector_111_x2.svg
    - assets/vectors/vector_90_x2.svg
    - assets/vectors/vector_3_x2.svg
    - assets/vectors/vector_79_x2.svg
    - assets/vectors/vector_32_x2.svg
    - assets/vectors/vector_50_x2.svg
    - assets/vectors/vector_35_x2.svg
    - assets/vectors/vector_102_x2.svg
    - assets/vectors/vector_75_x2.svg
    - assets/vectors/vector_72_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/vectors/vector_88_x2.svg
    - assets/vectors/vector_123_x2.svg
    - assets/vectors/vector_76_x2.svg
    - assets/vectors/vector_109_x2.svg
    - assets/vectors/vector_42_x2.svg
    - assets/vectors/vector_17_x2.svg
    - assets/images/image_171.png
    - assets/vectors/vector_63_x2.svg
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/vector_66_x2.svg
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_67_x2.svg
    - assets/vectors/vector_110_x2.svg
    - assets/vectors/vector_33_x2.svg
    - assets/vectors/vector_62_x2.svg
    - assets/vectors/vector_96_x2.svg
    - assets/vectors/vector_7_x2.svg
    - assets/vectors/vector_105_x2.svg
    - assets/vectors/vector_54_x2.svg
    - assets/vectors/vector_24_x2.svg
    - assets/vectors/vector_95_x2.svg
    - assets/vectors/vector_31_x2.svg
    - assets/vectors/vector_113_x2.svg
    - assets/vectors/map_x2.svg
    - assets/vectors/vector_58_x2.svg
    - assets/vectors/vector_118_x2.svg
    - assets/vectors/vector_93_x2.svg
    - assets/vectors/vector_112_x2.svg
    - assets/vectors/vector_13_x2.svg
    - assets/vectors/vector_56_x2.svg
    - assets/images/image_18.png
    - assets/vectors/vector_83_x2.svg
    - assets/vectors/vector_10_x2.svg
    - assets/vectors/vector_14_x2.svg
    - assets/vectors/vector_47_x2.svg
    - assets/vectors/vector_80_x2.svg
    - assets/vectors/vector_16_x2.svg
    - assets/vectors/vector_9_x2.svg
    - assets/vectors/group_3_x2.svg
    - assets/vectors/vector_x2.svg
    - assets/vectors/vector_29_x2.svg
    - assets/vectors/vector_55_x2.svg
    - assets/vectors/vector_115_x2.svg
    - assets/vectors/vector_25_x2.svg
